[package]
name = "multiboot2_chainloader"
description = "Multiboot chainloader that loads a Multiboot2 payload"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
util = { path = "../util" }
multiboot2 = { path = "../../../multiboot2" }
multiboot2-header = { path = "../../../multiboot2-header" }
anyhow = { version = "1.0", default-features = false }
elf_rs = "0.3"
log = { version = "0.4", default-features = false }
good_memory_allocator = "0.1"
multiboot = "0.8"
