[workspace]
resolver = "2"
members = [
    "multiboot2_chainloader",
    "multiboot2_payload",
    "util"
]

[profile.release]
codegen-units = 1
lto = true

[patch.crates-io]
multiboot2 = { path = "../../multiboot2" }
