[package]
name = "util"
description = "Util library"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
good_memory_allocator = "0.1"
log = { version = "0.4", default-features = false }
qemu-exit = "3.0.2"
